[package]
name = "wasi-vfs-cli"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "wasi-vfs"

[dependencies]
anyhow = "1.0.40"
structopt = "0.3.21"
wizer = { git = "https://github.com/bytecodealliance/wizer.git", rev = "1802237aeb8c19ff9448d67d280935bc10110d32" }
